### ISSUE TITLE
Issues during ROI registration

### ISSUE THREAD

**Issue by aron-adc** [DCBIA-OrthoLab/CMFreg#29] opened 2020-05-14 21:13 UTC
@luciacev @bpaniagua @jcfr 

Hi, here some issues with ROI registration option from Surface Registration module of SlicerCMF extension:

1) Landmarks size. When the user increases the size of the model (zoom it the model), the size of the landmark decreases, then the correct position of the landmark cannot be correctly confirmed.

2) Landmarks placement in different models (fixed and moving) in Dual 3D view. When the user places landmarks in one model (click on “add”) and before clicking to choose the correct position, if the cursor (arrow) passes to the other model and then returns to the previous one,  it automatically creates other landmarks for the first model. It happens ever when passing to the other model window. It could happen either when placing landmarks on the fixed or moving models. In other words, the cursor cannot pass through one of the models, otherwise when it returns more landmarks are created automatically.

3) ROI parameters. These problems with ROI were present in previous versions, as well. But, now it is worse. Ideally, it should allow the choice of “value of radius” whatever the user wants either in the fixed or the moving model. However, it happens some things:

    a.    It stops working from nothing. Sometimes, the user could click in clean mesh and the ROI parameter option works again. Other times, the ROI parameter option stops and the software stops and crushes forcing to close the software and open it again.

    b.     When some modifications have to be done to the “value of radius” of the ROI, the software slows progressively, sometimes stops and even closes automatically. Sometimes it only allows placing ROis in the fixed model and when the user tries to place them in the moving model, the software does not respond.

    c.     When the “value of the radius” does not need to be modified and runs ok, the software only allows one registration to be performed. When the user tries to perform a second registration, the software stops and the user needs to close the software and open it again.

The mentioned issues happen for both (for Windows and macOS) Preview Release version of Slicer 4.11.0 (even in the new one, built 2020-05-14).

Thank you very much,
Regards,

**Comment by luciacev** [comment] 2020-05-19 15:18
@JEHoctor
@bpaniagua 
@aron-adc 
@jcfr 
 
Please reach out to Aron if you need more information (screenshots or screen recording) to fix the issues he reported with the Surface Registration Module of CMFreg.

A number of users performing Surface registration are unable to use Slicer 4.11 due to these issues.  Thanks so much for your efforts!!

**Comment by bpaniagua** [comment] 2020-06-17 13:05
Hi @aron-adc 


Can you please send us the data you used to encounter those issues?
Thank you,

Bea

**Comment by aron-adc** [comment] 2020-06-17 14:33
Hi @luciacev @bpaniagua @JEHoctor 

Hope you are fine. I have just uploaded two .vtk files  and three videos in the folder [DCBIA>Slicer issues>CMFreg Issue#29](https://drive.google.com/drive/u/0/folders/1BvzbvpJo_8Fo-a_zbxtZj3OE0coXYfby) on Google Drive:
* [A1MxT1oriented.vtk](https://drive.google.com/file/d/1JKH6IjcMWatoQ9FwkM5r8S68FrY2ZzvR/view?usp=sharing)
* [A1MxT2apT1.vtk](https://drive.google.com/file/d/1JVr2TkujKi-eTtkJ6dHZHAvy2yaLEAh-/view?usp=sharing)

Regarding the previous reported issues:

1) Landmark size. It is resolved. After creating the MarkupsFiducial List. Click in Markups module--Display--Glyph Size: click in absolute. So, it will consider the absolute instead of percentage size and the landmark size will be maintained when increasing the model size (zoom it). I have not seen this option. I am sorry. So, no need to fix anything with this issue. That is ok. Thank you

2) Add Landmark. I attached a video ([CMFreg_Issue29_#2](https://drive.google.com/file/d/1girY_FnQdLJ3D9h1okXJA4wq4AG6C_AU/view?usp=sharing)) to better explain this issue. The problem is showed specifically from second 40. In the fixed model; landmarks T1-1 and T1-2 were adequately added, the problem is shown from landmark T1-3 to T1-6. In the moving model, landmarks T2-1 and T2-2 were adequately added, the problem is shown from landmark T2-3 to T2-7. Similar issue is happening in Q3DC when adding landmarks (i will report it too, as a separately issue)

3) registration. I attached two videos:
([CMFreg_Issue29_#3a](https://drive.google.com/file/d/1lVHPwZLgeTvd11MvarJwlPwuU0wLtaT4/view?usp=sharing)) with a simple problem. From second 33, the function does not respond  anymore, it stopped working and I had to restart the software.
([CMFreg_Issue29_#3b](https://drive.google.com/file/d/1A3i_67y4OLHKEJkEdBfZ8Pz5gwyu4fLn/view?usp=sharing)) it only allows placing ROis in the fixed model and when the user tries to place them in the moving model, the software begin to have delays (rois 1 and 2 in the moving model see video, 1´25´´) or does not respond (roi 3 in the moving model see video, 1´44´´) even when clicking on in clean mesh.



Thank you.

**Comment by jcfr** [comment] 2020-06-17 15:36
Thanks for the update.

Few tips for writing markdown:

* Prefer `1) Landmark size.` instead of `#1) Landmark size.`. Using `#N` will incorrectly reference issue with the number `N`

* To include link you can use the syntax `[short text](https://link/to/site-or-file)`. 
  * <s>Knowing that, could you edit the description above to include links ?</s> I took care of editing the description

**Comment by aron-adc** [comment] 2020-06-17 16:48
@jcfr Thank you four your tips and for editing the description. I have uploaded one more video and its description.

**Comment by allemangD** [comment] 2020-07-07 14:00
@luciacev, @aron-adc - The fix for these issues has been merged. Can you please check the nightly build tomorrow and verify that the issue is resolved?

**Closed as completed** 2020-08-21 15:14 UTC
